apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forex-app
  template:
    metadata:
      labels:
        app: forex-app
    spec:
      containers:
      - name: forex-app
        image: forex-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FOREX_API_KEY
          valueFrom:
            secretKeyRef:
              name: forex-secrets
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: forex-app-service
spec:
  selector:
    app: forex-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer